

server.port=8081   # changed from default 8080 (frontend was conflicting)
spring.datasource.url=jdbc:mysql://localhost:3306/wqm_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=omlet   # TODO: move this to env variable later
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


